## What is numpy?

* NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

## How are list different from Numpy?

### Numpy

* numpy is fast 
* Because it convert number into binary number in int(32, 16, 8) and it takes less bytes memory so its fast.
* No type checking when iterating through objects
* you can do methematical operation in it like(+,_,*,%,/)

### List

* list is slow 
* it require more memory bytes for store value.
* you can not do any math operation in it.

## Load numpy

In [2]:
import numpy as np

## The Basic

In [87]:
# Create array using list
my_list = [1,2,3]
my_list

[1, 2, 3]

In [88]:
np.array(my_list)

array([1, 2, 3])

In [89]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [90]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Create array with numpy 
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[3.0,4.0,5.0],[9.0,8.0,7.0]])
print(b)

[[3. 4. 5.]
 [9. 8. 7.]]


In [91]:
# arange func.
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
# linspace
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [5]:
# Get Dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get Shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
# Get Type
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('float64')

In [12]:
# Get Size
a.itemsize

4

In [14]:
# Get total size (a.size * a.itemsize)
a.nbytes

12

## Accessing/Changing specific elements, rows, columns etc

In [23]:
a = np.array([[11,12,13,14,15,16,17],[18,19,20,21,22,23,24]])
print(a)

[[11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24]]


In [24]:
# Get a specific elemet [r,c] (also use negetive index)
a[1, 5]

23

In [25]:
# Get specific row
a[0, :]

array([11, 12, 13, 14, 15, 16, 17])

In [26]:
# Get a specific column
a[:, 2]

array([13, 20])

In [27]:
# Get value using steps [startindex:endindex:stepsize]
a[0, 1:6:2]

array([12, 14, 16])

In [29]:
a[0, 1:-1:2]  # negetive index

array([12, 14, 16])

In [31]:
a[1,5] = 1
print(a)

a[:,2] =5
print(a)

[[11 12 13 14 15 16 17]
 [18 19 20 21 22  1 24]]
[[11 12  5 14 15 16 17]
 [18 19  5 21 22  1 24]]


In [33]:
# 3-d ex.
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
# Get specific element
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [37]:
b[0,1,1]

4

In [38]:
# replace
b[:,1,:] = [[9,9],[8,8]]

In [39]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Different types of arrays

In [42]:
# All 0s matrix
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [45]:
# any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [46]:
# full_like method
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [47]:
#Other method
np.full(a.shape, 4)     

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [48]:
# ranom decimal numbers
np.random.rand(4,2)

array([[0.55624544, 0.05562157],
       [0.01949481, 0.9827576 ],
       [0.28483702, 0.57076012],
       [0.67296329, 0.06750615]])

In [49]:
np.random.rand(5,3,4)

array([[[0.56652157, 0.6841964 , 0.8659139 , 0.72358149],
        [0.28500359, 0.91149411, 0.38539204, 0.74700176],
        [0.37487056, 0.24012611, 0.31050437, 0.18809454]],

       [[0.8486697 , 0.0386573 , 0.82975132, 0.185108  ],
        [0.18396573, 0.84856531, 0.29381008, 0.38262574],
        [0.10614955, 0.56415781, 0.80040403, 0.80328033]],

       [[0.12710435, 0.50846907, 0.24411393, 0.46088872],
        [0.88362224, 0.88070475, 0.06327679, 0.52698599],
        [0.34357861, 0.39295361, 0.6808637 , 0.19160895]],

       [[0.31053415, 0.83596701, 0.54758107, 0.72940331],
        [0.18697077, 0.44078868, 0.50847061, 0.32519803],
        [0.5923132 , 0.71212664, 0.38290925, 0.80248383]],

       [[0.09101151, 0.0601376 , 0.25089201, 0.86783475],
        [0.30503587, 0.00770474, 0.32390592, 0.91822793],
        [0.54093135, 0.81270835, 0.39517785, 0.63027232]]])

In [50]:
np.random.random_sample(a.shape)

array([[0.56744902, 0.16633272, 0.67371805, 0.19801577, 0.24027785,
        0.95449897, 0.77732384],
       [0.45358556, 0.33740819, 0.82257828, 0.17791076, 0.44683279,
        0.19229906, 0.5973122 ]])

In [93]:
# randn 
np.random.randn(5,5)

array([[ 0.56392743,  1.28552851, -1.40173248,  0.47713583, -0.42827082],
       [-1.45992562,  1.9112601 ,  1.04206524, -1.63988648, -0.61950937],
       [-0.80370957, -0.05476998,  2.19635589,  1.5191202 ,  0.66812994],
       [-1.05992065,  0.52487946,  0.29042946,  0.01793587, -1.38881393],
       [-1.17406123,  1.05116331, -0.61695349,  0.76489792,  1.05952454]])

In [51]:
# Random Integer values
np.random.randint(7, size=(3,3))

array([[3, 0, 2],
       [5, 0, 5],
       [0, 3, 6]])

In [52]:
np.random.randint(-4,8, size=(4,4))

array([[ 2,  5,  6,  2],
       [ 3,  4, -2,  4],
       [ 3,  5,  5,  6],
       [-3,  4,  3,  5]])

In [53]:
# The indentity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when copying arrays!!!

In [60]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)


[1 2 3]


## Mathmetics

In [61]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [62]:
a + 2

array([3, 4, 5, 6])

In [63]:
a - 2

array([-1,  0,  1,  2])

In [64]:
a * 2

array([2, 4, 6, 8])

In [65]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [66]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [67]:
a ** 2

array([ 1,  4,  9, 16])

## max, min, argmax, argmin

In [95]:
ranarr = np.random.randint(0,50,10)
print(ranarr)

[43 43 17  2 41 33 10 19 27 22]


In [96]:
ranarr.max()

43

In [97]:
ranarr.argmax()

0

In [98]:
ranarr.min()

2

In [99]:
ranarr.argmin()

3

## Universal Array Function

In [107]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
# Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [109]:
# Calculating Exponetial (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [110]:
# Trignometric
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [111]:
# Natural Logarithm
np.log(arr)

C:\Users\Yatharth Pandya\AppData\Local\Temp\ipykernel_9472\1970276075.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Statistics on Arrays

In [112]:
arr.sum()

45

In [113]:
arr.mean()

4.5

In [114]:
arr.max()

9

<strong>Other summary statistics include:</strong>
<pre>
arr.min() returns 0                   minimum
arr.var() returns 8.25                variance
arr.std() returns 2.8722813232690143  standard deviation
</pre>

## Reorganizing Arrays

In [83]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

after = before.reshape((2,2,2))
print(after)

(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [84]:
after = before.reshape((2,3))
print(after)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [85]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [100]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [102]:
bool_arr = arr>4


In [103]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [104]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [105]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])